// Generated by gencpp from file global_planer/Nav.msg
// DO NOT EDIT!


#ifndef GLOBAL_PLANER_MESSAGE_NAV_H
#define GLOBAL_PLANER_MESSAGE_NAV_H

#include <ros/service_traits.h>


#include <global_planer/NavRequest.h>
#include <global_planer/NavResponse.h>


namespace global_planer
{

struct Nav
{

typedef NavRequest Request;
typedef NavResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Nav
} // namespace global_planer


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::global_planer::Nav > {
  static const char* value()
  {
    return "dc45d88fed60392a91694173e2278679";
  }

  static const char* value(const ::global_planer::Nav&) { return value(); }
};

template<>
struct DataType< ::global_planer::Nav > {
  static const char* value()
  {
    return "global_planer/Nav";
  }

  static const char* value(const ::global_planer::Nav&) { return value(); }
};


// service_traits::MD5Sum< ::global_planer::NavRequest> should match
// service_traits::MD5Sum< ::global_planer::Nav >
template<>
struct MD5Sum< ::global_planer::NavRequest>
{
  static const char* value()
  {
    return MD5Sum< ::global_planer::Nav >::value();
  }
  static const char* value(const ::global_planer::NavRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::global_planer::NavRequest> should match
// service_traits::DataType< ::global_planer::Nav >
template<>
struct DataType< ::global_planer::NavRequest>
{
  static const char* value()
  {
    return DataType< ::global_planer::Nav >::value();
  }
  static const char* value(const ::global_planer::NavRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::global_planer::NavResponse> should match
// service_traits::MD5Sum< ::global_planer::Nav >
template<>
struct MD5Sum< ::global_planer::NavResponse>
{
  static const char* value()
  {
    return MD5Sum< ::global_planer::Nav >::value();
  }
  static const char* value(const ::global_planer::NavResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::global_planer::NavResponse> should match
// service_traits::DataType< ::global_planer::Nav >
template<>
struct DataType< ::global_planer::NavResponse>
{
  static const char* value()
  {
    return DataType< ::global_planer::Nav >::value();
  }
  static const char* value(const ::global_planer::NavResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // GLOBAL_PLANER_MESSAGE_NAV_H
