// Generated by gencpp from file global_planer/nav.msg
// DO NOT EDIT!


#ifndef GLOBAL_PLANER_MESSAGE_NAV_H
#define GLOBAL_PLANER_MESSAGE_NAV_H

#include <ros/service_traits.h>


#include <global_planer/navRequest.h>
#include <global_planer/navResponse.h>


namespace global_planer
{

struct nav
{

typedef navRequest Request;
typedef navResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct nav
} // namespace global_planer


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::global_planer::nav > {
  static const char* value()
  {
    return "dc45d88fed60392a91694173e2278679";
  }

  static const char* value(const ::global_planer::nav&) { return value(); }
};

template<>
struct DataType< ::global_planer::nav > {
  static const char* value()
  {
    return "global_planer/nav";
  }

  static const char* value(const ::global_planer::nav&) { return value(); }
};


// service_traits::MD5Sum< ::global_planer::navRequest> should match
// service_traits::MD5Sum< ::global_planer::nav >
template<>
struct MD5Sum< ::global_planer::navRequest>
{
  static const char* value()
  {
    return MD5Sum< ::global_planer::nav >::value();
  }
  static const char* value(const ::global_planer::navRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::global_planer::navRequest> should match
// service_traits::DataType< ::global_planer::nav >
template<>
struct DataType< ::global_planer::navRequest>
{
  static const char* value()
  {
    return DataType< ::global_planer::nav >::value();
  }
  static const char* value(const ::global_planer::navRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::global_planer::navResponse> should match
// service_traits::MD5Sum< ::global_planer::nav >
template<>
struct MD5Sum< ::global_planer::navResponse>
{
  static const char* value()
  {
    return MD5Sum< ::global_planer::nav >::value();
  }
  static const char* value(const ::global_planer::navResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::global_planer::navResponse> should match
// service_traits::DataType< ::global_planer::nav >
template<>
struct DataType< ::global_planer::navResponse>
{
  static const char* value()
  {
    return DataType< ::global_planer::nav >::value();
  }
  static const char* value(const ::global_planer::navResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // GLOBAL_PLANER_MESSAGE_NAV_H
