# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from styx_msgs/NavRequest.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import geometry_msgs.msg
import std_msgs.msg

class NavRequest(genpy.Message):
  _md5sum = "105471b4ec03125dccde71d28fbfdb8e"
  _type = "styx_msgs/NavRequest"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """# Client 
float32 currentTime
geometry_msgs/PoseStamped currentPose
geometry_msgs/TwistStamped currentTwist

================================================================================
MSG: geometry_msgs/PoseStamped
# A Pose with reference coordinate frame and timestamp
Header header
Pose pose

================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
string frame_id

================================================================================
MSG: geometry_msgs/Pose
# A representation of pose in free space, composed of position and orientation. 
Point position
Quaternion orientation

================================================================================
MSG: geometry_msgs/Point
# This contains the position of a point in free space
float64 x
float64 y
float64 z

================================================================================
MSG: geometry_msgs/Quaternion
# This represents an orientation in free space in quaternion form.

float64 x
float64 y
float64 z
float64 w

================================================================================
MSG: geometry_msgs/TwistStamped
# A twist with reference coordinate frame and timestamp
Header header
Twist twist

================================================================================
MSG: geometry_msgs/Twist
# This expresses velocity in free space broken into its linear and angular parts.
Vector3  linear
Vector3  angular

================================================================================
MSG: geometry_msgs/Vector3
# This represents a vector in free space. 
# It is only meant to represent a direction. Therefore, it does not
# make sense to apply a translation to it (e.g., when applying a 
# generic rigid transformation to a Vector3, tf2 will only apply the
# rotation). If you want your data to be translatable too, use the
# geometry_msgs/Point message instead.

float64 x
float64 y
float64 z"""
  __slots__ = ['currentTime','currentPose','currentTwist']
  _slot_types = ['float32','geometry_msgs/PoseStamped','geometry_msgs/TwistStamped']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       currentTime,currentPose,currentTwist

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(NavRequest, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.currentTime is None:
        self.currentTime = 0.
      if self.currentPose is None:
        self.currentPose = geometry_msgs.msg.PoseStamped()
      if self.currentTwist is None:
        self.currentTwist = geometry_msgs.msg.TwistStamped()
    else:
      self.currentTime = 0.
      self.currentPose = geometry_msgs.msg.PoseStamped()
      self.currentTwist = geometry_msgs.msg.TwistStamped()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_f3I().pack(_x.currentTime, _x.currentPose.header.seq, _x.currentPose.header.stamp.secs, _x.currentPose.header.stamp.nsecs))
      _x = self.currentPose.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_7d3I().pack(_x.currentPose.pose.position.x, _x.currentPose.pose.position.y, _x.currentPose.pose.position.z, _x.currentPose.pose.orientation.x, _x.currentPose.pose.orientation.y, _x.currentPose.pose.orientation.z, _x.currentPose.pose.orientation.w, _x.currentTwist.header.seq, _x.currentTwist.header.stamp.secs, _x.currentTwist.header.stamp.nsecs))
      _x = self.currentTwist.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_6d().pack(_x.currentTwist.twist.linear.x, _x.currentTwist.twist.linear.y, _x.currentTwist.twist.linear.z, _x.currentTwist.twist.angular.x, _x.currentTwist.twist.angular.y, _x.currentTwist.twist.angular.z))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.currentPose is None:
        self.currentPose = geometry_msgs.msg.PoseStamped()
      if self.currentTwist is None:
        self.currentTwist = geometry_msgs.msg.TwistStamped()
      end = 0
      _x = self
      start = end
      end += 16
      (_x.currentTime, _x.currentPose.header.seq, _x.currentPose.header.stamp.secs, _x.currentPose.header.stamp.nsecs,) = _get_struct_f3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.currentPose.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.currentPose.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 68
      (_x.currentPose.pose.position.x, _x.currentPose.pose.position.y, _x.currentPose.pose.position.z, _x.currentPose.pose.orientation.x, _x.currentPose.pose.orientation.y, _x.currentPose.pose.orientation.z, _x.currentPose.pose.orientation.w, _x.currentTwist.header.seq, _x.currentTwist.header.stamp.secs, _x.currentTwist.header.stamp.nsecs,) = _get_struct_7d3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.currentTwist.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.currentTwist.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 48
      (_x.currentTwist.twist.linear.x, _x.currentTwist.twist.linear.y, _x.currentTwist.twist.linear.z, _x.currentTwist.twist.angular.x, _x.currentTwist.twist.angular.y, _x.currentTwist.twist.angular.z,) = _get_struct_6d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_f3I().pack(_x.currentTime, _x.currentPose.header.seq, _x.currentPose.header.stamp.secs, _x.currentPose.header.stamp.nsecs))
      _x = self.currentPose.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_7d3I().pack(_x.currentPose.pose.position.x, _x.currentPose.pose.position.y, _x.currentPose.pose.position.z, _x.currentPose.pose.orientation.x, _x.currentPose.pose.orientation.y, _x.currentPose.pose.orientation.z, _x.currentPose.pose.orientation.w, _x.currentTwist.header.seq, _x.currentTwist.header.stamp.secs, _x.currentTwist.header.stamp.nsecs))
      _x = self.currentTwist.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_6d().pack(_x.currentTwist.twist.linear.x, _x.currentTwist.twist.linear.y, _x.currentTwist.twist.linear.z, _x.currentTwist.twist.angular.x, _x.currentTwist.twist.angular.y, _x.currentTwist.twist.angular.z))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.currentPose is None:
        self.currentPose = geometry_msgs.msg.PoseStamped()
      if self.currentTwist is None:
        self.currentTwist = geometry_msgs.msg.TwistStamped()
      end = 0
      _x = self
      start = end
      end += 16
      (_x.currentTime, _x.currentPose.header.seq, _x.currentPose.header.stamp.secs, _x.currentPose.header.stamp.nsecs,) = _get_struct_f3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.currentPose.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.currentPose.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 68
      (_x.currentPose.pose.position.x, _x.currentPose.pose.position.y, _x.currentPose.pose.position.z, _x.currentPose.pose.orientation.x, _x.currentPose.pose.orientation.y, _x.currentPose.pose.orientation.z, _x.currentPose.pose.orientation.w, _x.currentTwist.header.seq, _x.currentTwist.header.stamp.secs, _x.currentTwist.header.stamp.nsecs,) = _get_struct_7d3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.currentTwist.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.currentTwist.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 48
      (_x.currentTwist.twist.linear.x, _x.currentTwist.twist.linear.y, _x.currentTwist.twist.linear.z, _x.currentTwist.twist.angular.x, _x.currentTwist.twist.angular.y, _x.currentTwist.twist.angular.z,) = _get_struct_6d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_6d = None
def _get_struct_6d():
    global _struct_6d
    if _struct_6d is None:
        _struct_6d = struct.Struct("<6d")
    return _struct_6d
_struct_7d3I = None
def _get_struct_7d3I():
    global _struct_7d3I
    if _struct_7d3I is None:
        _struct_7d3I = struct.Struct("<7d3I")
    return _struct_7d3I
_struct_f3I = None
def _get_struct_f3I():
    global _struct_f3I
    if _struct_f3I is None:
        _struct_f3I = struct.Struct("<f3I")
    return _struct_f3I
# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from styx_msgs/NavResponse.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import geometry_msgs.msg
import std_msgs.msg

class NavResponse(genpy.Message):
  _md5sum = "724eadc8f87261a62f785aa244ebcc1d"
  _type = "styx_msgs/NavResponse"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """# Server
geometry_msgs/PoseStamped targetPose
geometry_msgs/TwistStamped targetTwist
float32 kappa


================================================================================
MSG: geometry_msgs/PoseStamped
# A Pose with reference coordinate frame and timestamp
Header header
Pose pose

================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
string frame_id

================================================================================
MSG: geometry_msgs/Pose
# A representation of pose in free space, composed of position and orientation. 
Point position
Quaternion orientation

================================================================================
MSG: geometry_msgs/Point
# This contains the position of a point in free space
float64 x
float64 y
float64 z

================================================================================
MSG: geometry_msgs/Quaternion
# This represents an orientation in free space in quaternion form.

float64 x
float64 y
float64 z
float64 w

================================================================================
MSG: geometry_msgs/TwistStamped
# A twist with reference coordinate frame and timestamp
Header header
Twist twist

================================================================================
MSG: geometry_msgs/Twist
# This expresses velocity in free space broken into its linear and angular parts.
Vector3  linear
Vector3  angular

================================================================================
MSG: geometry_msgs/Vector3
# This represents a vector in free space. 
# It is only meant to represent a direction. Therefore, it does not
# make sense to apply a translation to it (e.g., when applying a 
# generic rigid transformation to a Vector3, tf2 will only apply the
# rotation). If you want your data to be translatable too, use the
# geometry_msgs/Point message instead.

float64 x
float64 y
float64 z"""
  __slots__ = ['targetPose','targetTwist','kappa']
  _slot_types = ['geometry_msgs/PoseStamped','geometry_msgs/TwistStamped','float32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       targetPose,targetTwist,kappa

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(NavResponse, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.targetPose is None:
        self.targetPose = geometry_msgs.msg.PoseStamped()
      if self.targetTwist is None:
        self.targetTwist = geometry_msgs.msg.TwistStamped()
      if self.kappa is None:
        self.kappa = 0.
    else:
      self.targetPose = geometry_msgs.msg.PoseStamped()
      self.targetTwist = geometry_msgs.msg.TwistStamped()
      self.kappa = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.targetPose.header.seq, _x.targetPose.header.stamp.secs, _x.targetPose.header.stamp.nsecs))
      _x = self.targetPose.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_7d3I().pack(_x.targetPose.pose.position.x, _x.targetPose.pose.position.y, _x.targetPose.pose.position.z, _x.targetPose.pose.orientation.x, _x.targetPose.pose.orientation.y, _x.targetPose.pose.orientation.z, _x.targetPose.pose.orientation.w, _x.targetTwist.header.seq, _x.targetTwist.header.stamp.secs, _x.targetTwist.header.stamp.nsecs))
      _x = self.targetTwist.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_6df().pack(_x.targetTwist.twist.linear.x, _x.targetTwist.twist.linear.y, _x.targetTwist.twist.linear.z, _x.targetTwist.twist.angular.x, _x.targetTwist.twist.angular.y, _x.targetTwist.twist.angular.z, _x.kappa))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.targetPose is None:
        self.targetPose = geometry_msgs.msg.PoseStamped()
      if self.targetTwist is None:
        self.targetTwist = geometry_msgs.msg.TwistStamped()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.targetPose.header.seq, _x.targetPose.header.stamp.secs, _x.targetPose.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.targetPose.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.targetPose.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 68
      (_x.targetPose.pose.position.x, _x.targetPose.pose.position.y, _x.targetPose.pose.position.z, _x.targetPose.pose.orientation.x, _x.targetPose.pose.orientation.y, _x.targetPose.pose.orientation.z, _x.targetPose.pose.orientation.w, _x.targetTwist.header.seq, _x.targetTwist.header.stamp.secs, _x.targetTwist.header.stamp.nsecs,) = _get_struct_7d3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.targetTwist.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.targetTwist.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 52
      (_x.targetTwist.twist.linear.x, _x.targetTwist.twist.linear.y, _x.targetTwist.twist.linear.z, _x.targetTwist.twist.angular.x, _x.targetTwist.twist.angular.y, _x.targetTwist.twist.angular.z, _x.kappa,) = _get_struct_6df().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.targetPose.header.seq, _x.targetPose.header.stamp.secs, _x.targetPose.header.stamp.nsecs))
      _x = self.targetPose.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_7d3I().pack(_x.targetPose.pose.position.x, _x.targetPose.pose.position.y, _x.targetPose.pose.position.z, _x.targetPose.pose.orientation.x, _x.targetPose.pose.orientation.y, _x.targetPose.pose.orientation.z, _x.targetPose.pose.orientation.w, _x.targetTwist.header.seq, _x.targetTwist.header.stamp.secs, _x.targetTwist.header.stamp.nsecs))
      _x = self.targetTwist.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_6df().pack(_x.targetTwist.twist.linear.x, _x.targetTwist.twist.linear.y, _x.targetTwist.twist.linear.z, _x.targetTwist.twist.angular.x, _x.targetTwist.twist.angular.y, _x.targetTwist.twist.angular.z, _x.kappa))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.targetPose is None:
        self.targetPose = geometry_msgs.msg.PoseStamped()
      if self.targetTwist is None:
        self.targetTwist = geometry_msgs.msg.TwistStamped()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.targetPose.header.seq, _x.targetPose.header.stamp.secs, _x.targetPose.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.targetPose.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.targetPose.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 68
      (_x.targetPose.pose.position.x, _x.targetPose.pose.position.y, _x.targetPose.pose.position.z, _x.targetPose.pose.orientation.x, _x.targetPose.pose.orientation.y, _x.targetPose.pose.orientation.z, _x.targetPose.pose.orientation.w, _x.targetTwist.header.seq, _x.targetTwist.header.stamp.secs, _x.targetTwist.header.stamp.nsecs,) = _get_struct_7d3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.targetTwist.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.targetTwist.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 52
      (_x.targetTwist.twist.linear.x, _x.targetTwist.twist.linear.y, _x.targetTwist.twist.linear.z, _x.targetTwist.twist.angular.x, _x.targetTwist.twist.angular.y, _x.targetTwist.twist.angular.z, _x.kappa,) = _get_struct_6df().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
_struct_6df = None
def _get_struct_6df():
    global _struct_6df
    if _struct_6df is None:
        _struct_6df = struct.Struct("<6df")
    return _struct_6df
_struct_7d3I = None
def _get_struct_7d3I():
    global _struct_7d3I
    if _struct_7d3I is None:
        _struct_7d3I = struct.Struct("<7d3I")
    return _struct_7d3I
class Nav(object):
  _type          = 'styx_msgs/Nav'
  _md5sum = '4c1397c5940b771e71cd0ee42abe5307'
  _request_class  = NavRequest
  _response_class = NavResponse
