// Generated by gencpp from file styx_msgs/Nav.msg
// DO NOT EDIT!


#ifndef STYX_MSGS_MESSAGE_NAV_H
#define STYX_MSGS_MESSAGE_NAV_H

#include <ros/service_traits.h>


#include <styx_msgs/NavRequest.h>
#include <styx_msgs/NavResponse.h>


namespace styx_msgs
{

struct Nav
{

typedef NavRequest Request;
typedef NavResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Nav
} // namespace styx_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::styx_msgs::Nav > {
  static const char* value()
  {
    return "4c1397c5940b771e71cd0ee42abe5307";
  }

  static const char* value(const ::styx_msgs::Nav&) { return value(); }
};

template<>
struct DataType< ::styx_msgs::Nav > {
  static const char* value()
  {
    return "styx_msgs/Nav";
  }

  static const char* value(const ::styx_msgs::Nav&) { return value(); }
};


// service_traits::MD5Sum< ::styx_msgs::NavRequest> should match
// service_traits::MD5Sum< ::styx_msgs::Nav >
template<>
struct MD5Sum< ::styx_msgs::NavRequest>
{
  static const char* value()
  {
    return MD5Sum< ::styx_msgs::Nav >::value();
  }
  static const char* value(const ::styx_msgs::NavRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::styx_msgs::NavRequest> should match
// service_traits::DataType< ::styx_msgs::Nav >
template<>
struct DataType< ::styx_msgs::NavRequest>
{
  static const char* value()
  {
    return DataType< ::styx_msgs::Nav >::value();
  }
  static const char* value(const ::styx_msgs::NavRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::styx_msgs::NavResponse> should match
// service_traits::MD5Sum< ::styx_msgs::Nav >
template<>
struct MD5Sum< ::styx_msgs::NavResponse>
{
  static const char* value()
  {
    return MD5Sum< ::styx_msgs::Nav >::value();
  }
  static const char* value(const ::styx_msgs::NavResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::styx_msgs::NavResponse> should match
// service_traits::DataType< ::styx_msgs::Nav >
template<>
struct DataType< ::styx_msgs::NavResponse>
{
  static const char* value()
  {
    return DataType< ::styx_msgs::Nav >::value();
  }
  static const char* value(const ::styx_msgs::NavResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // STYX_MSGS_MESSAGE_NAV_H
